name: Engine Bugs/Errors
description: Report bugs with the engine. Any compiling issues should be put in Help
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: "Describe your issue here."
    validations:
      required: true

  - type: textarea
    id: terminal
    attributes:
      label: "Command Prompt/Terminal logs (if available)"
      render: bash
    validations:
      required: false

  - type: dropdown
    id: btarget
    attributes:
      label: "What is your build target?"
      options:
        - "Windows"
        - "Linux"
        - "Mac"
        - "HTML5"
    validations:
      required: true

  - type: input
    id: buildsummary
    attributes:
      label: "Did you edit anything in this build? If so, mention or summarize your changes."
      placeholder: "Yes, I edited Character.hx and tried to add a new character"
    validations:
      required: true
